[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[features]
default = ["capnp/std"]
no_std = ["capnp/embedded-io"]

[dependencies]
capnp = { version = "0.24.0", default-features = false, optional = true }

[build-dependencies]
capnpc = "0.24.0"
